version = "0.3.X"
defaultTheme: auto
ShowReadingTime = true
[page]
[page.math]
enable = true
blockLeftDelimiter = "\\["
blockRightDelimiter = "\\]"
inlineLeftDelimiter = "\\("
inlineRightDelimiter = "\\)"
copyTex = true
mhchem = true
[homeInfoParames]
Title = "Hi there wave"
Content = "welcome to my blog"