name: CD

on:
  push:
    branches:
      - 'main'

  schedule:
    # Runs every Sunday at 12:00 PM GMT+8 (04:00 UTC)
    - cron: '0 4 * * 0'
  workflow_dispatch:
    

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

env:
  NODE_VERSION: 16.x

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_PAGES_DEPLOY_HOOK: ${{ secrets.CLOUDFLARE_PAGES_DEPLOY_HOOK }}

    steps:
      - name: Trigger Cloudflare Pages build
        if: startsWith(env.CLOUDFLARE_PAGES_DEPLOY_HOOK, 'https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/') && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
        run: curl -X POST ${{ secrets.CLOUDFLARE_PAGES_DEPLOY_HOOK }}


      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.139.4'
          extended: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Hugo
        env: # Or as an environment variable
         NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: |
          npm install
          npm start

          find ./content -type f -name "*-*" -print0 | while IFS= read -r -d '' file; do
            dir=$(dirname "$file")
            base=$(basename "$file")
            # newbase 是把最后一个 '-' 及之后的字符都去掉
            newbase="${base%-*}"
            mv "$file" "$dir/$newbase"
          done

          hugo

      # - name: Commit updated content
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: Sync content with Notion

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
